name: my first action

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: my checkout who supposed to work
              uses: actions/checkout@v4
            
            - name: welcome messsage
              run: echo "hello Mr. Ezra"

            - name: list files
              run: ls

            - name: Read file
              run: cat README.md  